# Generated by Django 4.1.3 on 2022-11-04 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoteliaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_hotel', models.CharField(max_length=30, verbose_name='Nombre')),
                ('telefono_hotel', models.CharField(max_length=15, verbose_name='Telefono')),
                ('direccion_hotel', models.CharField(max_length=120, verbose_name='Direccion')),
                ('ciudad_hotel', models.CharField(max_length=30, verbose_name='Ciudad')),
                ('pais_hotel', models.CharField(max_length=30, verbose_name='Pais')),
                ('descripcion_hotel', models.TextField(max_length=1000, verbose_name='Descripcion')),
                ('estado_hotel', models.BooleanField(default=True, verbose_name='Estado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoteliaApp.account')),
            ],
        ),
    ]
