# Generated by Django 4.1.3 on 2022-11-05 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoteliaApp', '0003_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('costoServicio', models.FloatField(max_length=10)),
                ('descripcion', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaReserva', models.DateTimeField(auto_now_add=True)),
                ('fechaCheckIn', models.DateField()),
                ('fechaCheckOut', models.DateField()),
                ('medioPago', models.CharField(max_length=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hoteliaApp.account')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hoteliaApp.hotel')),
            ],
        ),
    ]
